apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rclone
  namespace: csi-rclone
provisioner: kubernetes.io/no-provisioner
#volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/node-publish-secret-name: rclone-secret
  csi.storage.k8s.io/node-publish-secret-namespace: csi-rclone
